camera_calibration_parameters:
    intrinsic_K: [534.4424, -0.0118, 631.33,
                  -0.0311, 521.9, 364.08,
                  0, 0, 1]
    extrinsic_P: [1.0, 0, 0, -0.0227,
                  0, 1.0, 0, -0.0111,
                  0, 0, 1.0, -0.0662,
                  0, 0, 0, 1.0]
    dist_coeffs: [0, 0, 0, 0, 0]
    save_cloud: false

input_topics:
    image_topic: "/zed2/zed_node/left/image_rect_color"
    cloud_topic: "/cloud_registered_body"
    odometry_topic: "/Odometry"
